version: '3.1'

services:
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9090:8080"
    deploy:
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
