version: '3.1'

services:

  portainer:
    image: portainer/portainer:1.15.2
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.docker.network=traefik-net"
        - "traefik.weight=10"
        - "traefik.frontend.passHostHeader=true"

networks:
  traefik-net:
    external: true


version: '3.3'

services:
  portainer:
    image: portainer/portainer
    command: --host unix:///var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:9000"
    networks:
      - portaineroverlay
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  portaineroverlay:
    driver: overlay

volumes:
  portainer_data:
